name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SHOULD_DEPLOY: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}


jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run tests
        run: npm test
      - name: Trigger deployment
        if: ${{ env.SHOULD_DEPLOY }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_KEY }}?key=${{ secrets.RENDER_API_KEY }}

  version_bump_and_tag:
    needs: simple_deployment_pipeline
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ env.SHOULD_DEPLOY }}
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default_bump: patch

  discord_notifications:
    needs: [simple_deployment_pipeline, version_bump_and_tag]
    runs-on: ubuntu-20.04
    steps:
      - name: Success Notification
        if: ${{ success() && env.SHOULD_DEPLOY }}
        uses: Ilshidur/action-discord@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            :white_check_mark: **Deployment Successful!**
            - **Version:** Bumped and deployed.
            - **Commit:** ${{ github.event.head_commit.message }}
            - **Committer:** ${{ github.event.head_commit.author.name }}
            - **Branch:** ${{ github.ref_name }}
            - :rocket: The new version is live! 🎉
      - name: Failure Notification
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            :x: **Build Failed!**
            - **Commit:** ${{ github.event.head_commit.message }}
            - **Committer:** ${{ github.event.head_commit.author.name }}
            - **Branch:** ${{ github.ref_name }}
            - **Error:** Job failure in step `${{ job.status }}`.
            - Please check the logs for more details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
